export const serializePublicFreelancer = (user, { includeEmail = false, badges = [], headline = '' } = {}) => ({
  id: String(user._id),
  firstName: user.firstName || '',
  lastName: user.lastName || '',
  ...(includeEmail ? { email: user.email || '' } : {}),
  freelancerId: user.freelancerId || '',
  bio: user.bio || '',
  professionalSummary: user.professionalSummary || '',
  skills: Array.isArray(user.skills) ? user.skills : [],
  profilePicture: user.profilePicture || '',
  degree: user.degree || '',
  schoolName: user.schoolName || '',
  city: user.city || '',
  country: user.country || '',
  certifications: user.certifications || [],
  projects: user.projects || [],
  headline: headline || '',
  badges,
});
